language: haskell

before_install:
  - wget http://libsdl.org/release/SDL2-2.0.3.tar.gz -O - | tar xz
  - cd SDL2-2.0.3 && ./configure && make -j && sudo make install && cd ..
  - cabal install --only-d

script:
  - cabal configure && cabal build

notifications:
  irc:
    channels:
      - "irc.freenode.net#haskell-game"
    skip_join: true
    template:
      - "\x0313sdl2\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
